name: Continuous Integration
on:
  pull_request:

jobs:
  scan:
    if: github.event_name == 'pull_request'
    uses: jscaltreto/circle-public-github-workflows/.github/workflows/pr-scan.yaml@forked-dependency-review-action
